[tools]
deno = "2.4.2"

[env]
_.file = ".env"

[tasks.start]
run = "smallweb up"

[tasks."docker:start"]
description = "Build and start Smallweb with docker-compose"
run = "docker-compose up --build"

[tasks."docker:stop"]
description = "Stop and remove docker containers"
run = "docker-compose down"

[tasks."get-ip"]
description = "Get the IP address of the smallweb droplet"
run = """
doctl compute droplet list --format Name,PublicIPv4 --no-header | grep smallweb | awk '{print $2}'
"""

[tasks.deploy]
description = "Deploy to DigitalOcean Droplet"
run = "deno run -A alchemy.run.ts"

[tasks.ssh]
description = "SSH into the deployment droplet"
run = """
DROPLET_IP=$(mise run get-ip)
if [ -z "$DROPLET_IP" ]; then
  echo "❌ No smallweb droplet found. Run 'mise run deploy' first."
  exit 1
fi
ssh -i ${SSH_KEY_PATH} root@$DROPLET_IP
"""

[tasks.logs]
description = "View deployment logs"
run = """
DROPLET_IP=$(mise run get-ip)
if [ -z "$DROPLET_IP" ]; then
  echo "❌ No smallweb droplet found. Run 'mise run deploy' first."
  exit 1
fi
ssh -i ${SSH_KEY_PATH} root@$DROPLET_IP 'docker logs -f smallweb'
"""

[tasks."deploy:status"]
description = "Check deployment status"
run = """
DROPLET_IP=$(mise run get-ip)
if [ -z "$DROPLET_IP" ]; then
  echo "❌ No smallweb droplet found. Run 'mise run deploy' first."
  exit 1
fi
echo "🖥️  Droplet IP: $DROPLET_IP"
ssh -i ${SSH_KEY_PATH} root@$DROPLET_IP 'docker ps | grep smallweb || echo "❌ Container not running"'
"""

[tasks.sync]
description = "Sync local files to Smallweb server"
run = """
echo "🔄 Syncing files to Smallweb server..."

# Get server IP
DROPLET_IP=$(mise run get-ip)

# Sync files using rsync through root SSH access
rsync -avz --delete \
  --exclude='.git' \
  --exclude='.DS_Store' \
  --exclude='node_modules' \
  --exclude='*.log' \
  --exclude='.env' \
  -e "ssh -i ${SSH_KEY_PATH}" \
  ./ root@$DROPLET_IP:/opt/docker/smallweb/data/

echo "✅ Sync complete!"
"""
