[tools]
"aqua:mutagen-io/mutagen" = "0.18.1"
deno = "2.4.2"

[env]
_.file = ".env"

[tasks.start]
run = "smallweb up"

[tasks."docker:start"]
description = "Build and start Smallweb with docker-compose"
run = "docker-compose up --build"

[tasks."docker:stop"]
description = "Stop and remove docker containers"
run = "docker-compose down"

[tasks.deploy]
description = "Deploy to DigitalOcean Droplet"
run = "deno run -A alchemy.run.ts"

[tasks."deploy:ssh"]
description = "SSH into the deployment droplet"
run = """
DROPLET_IP=$(doctl compute droplet list --format Name,PublicIPv4 --no-header | grep smallweb | awk '{print $2}')
if [ -z "$DROPLET_IP" ]; then
  echo "❌ No smallweb droplet found. Run 'mise run deploy' first."
  exit 1
fi
ssh root@$DROPLET_IP
"""

[tasks."deploy:logs"]
description = "View deployment logs"
run = """
DROPLET_IP=$(doctl compute droplet list --format Name,PublicIPv4 --no-header | grep smallweb | awk '{print $2}')
if [ -z "$DROPLET_IP" ]; then
  echo "❌ No smallweb droplet found. Run 'mise run deploy' first."
  exit 1
fi
ssh root@$DROPLET_IP 'docker logs -f smallweb'
"""

[tasks."deploy:status"]
description = "Check deployment status"
run = """
DROPLET_IP=$(doctl compute droplet list --format Name,PublicIPv4 --no-header | grep smallweb | awk '{print $2}')
if [ -z "$DROPLET_IP" ]; then
  echo "❌ No smallweb droplet found. Run 'mise run deploy' first."
  exit 1
fi
echo "🖥️  Droplet IP: $DROPLET_IP"
ssh root@$DROPLET_IP 'docker ps | grep smallweb || echo "❌ Container not running"'
"""
