name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build container image
        run: docker build -t registry.digitalocean.com/${{ secrets.DIGITALOCEAN_REGISTRY }}/smallweb:${{ github.sha }} .

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 1200

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/${{ secrets.DIGITALOCEAN_REGISTRY }}/smallweb:${{ github.sha }}

      - name: Deploy to DigitalOcean App Platform
        run: doctl apps create-deployment ${{ secrets.DIGITALOCEAN_APP_ID }} --image-source-digest registry.digitalocean.com/${{ secrets.DIGITALOCEAN_REGISTRY }}/smallweb:${{ github.sha }}